### ISSUE TITLE
got an unexpected keyword argument 'voice_channel_ids'

### ISSUE THREAD

**Issue by AandyLi** [brakhane/Orisa#2]
Hi. I wanted to try out your bot and finally got all the libs working but when i start the bot i get the following:

> C:\Users\andre\Desktop\Orisa>python orisa.py
Traceback (most recent call last):
  File "orisa.py", line 72, in <module>
    from config import BOT_TOKEN, CHANNEL_NAMES, GLADOS_TOKEN, GUILD_INFOS, MASHERY_API_KEY, SENTRY_DSN
  File "C:\Users\andre\Desktop\Orisa\config.py", line 37, in <module>
    wow_listen_channel_id=123,
TypeError: __init__() got an unexpected keyword argument 'voice_channel_ids'

I have tried to edit the voice_channel_ids list but nothing seems to be working. Am i doing something wrong?

**Comment by brakhane** [comment]
Hi. Thank you for your interest.

As stated in the README, it would be easier if the working Orisa instance could be invited to your server; I'm actually working on some features to make her configurable by server owners.

If you still want to run your own instance, be advised that there are currently quite a few changes and extensions in work, most of which are not documented.

Nevertheless, I've just pushed an update that should at least have the correct config template.

Be advised that you currently need the git version of the curious library, the 0.7 branch. The version released on PyPI right now still has some critical bugs (you can see my PR there; there are quite a few)

But as I said, I'd **much** prefer it if my currently running instance could handle your server as well. She already handles 2, but having more is good to work out the kinks. (And having people who will use the upcoming guild configuration features (who aren't me) would help me as well). 
It would also be much easier for you; **keeping** Orisa running currently requires some knowledge on how she works, which is not documented at the moment.

**Comment by AandyLi** [comment]
Hello again. Thanks for pushing the update! The bot is now running on my discord.

I think for the time being I'll try to run the bot my self. My discord server is at the moment not active and i want to try and set it up properly before i start to invite players. If and when the server becomes active with users we could try to have you run an instance of it.

Orisa is actually the only bot i found who would scan players sr automatically and update it in the discord, which i think is an awesome feature although i just tried to get a friend to register his battletag with no success. 

Sadly i dont know enough python to be able to contribute but I'll keep an eye out for updates! :)
